---
- name: Create a redis instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: SetOne
    instance_type: t2.medium
    security_group: launch-wizard-1
    image: ami-059eeca93cf09eebd
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-f82a8ed4
         assign_public_ip: yes
         instance_tags:
             name: redis
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles: 
    - geerlingguy.redis
