---
- name: start instance
  hosts: localhost

  tasks:
    - local_action:
        module: ec2
        region: "{{ region }}"
        instance_tags:
            Name: ExtraPower
        state: running
